services:
  - type: web
    name: instagram-profile-api
    runtime: node
    rootDir: api
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
